[package]
name = "data-channel"
version = "0.1.0"
edition = "2021"

[dependencies]
nrf-softdevice = { version = "0.1.0", features = ["ble-l2cap"] }
nrf-softdevice-s140 = { version = "0.1.1" }
defmt = "0.3"
