# Make sure this is the same version as in the embassy repository.

[toolchain]
channel = "nightly-2023-11-01"
components = [ "rust-src", "rustfmt", "llvm-tools" ]
targets = [
  "thumbv7em-none-eabihf",
]
